import './globals.css'
import { Poppins } from 'next/font/google'
import Footer from './components/Footer'

const pop = Poppins({
  weight: ['400', '500', '600', '300'],
  subsets: ['latin'],
  variable: '--font-poppins',
})

export const metadata = {
  title: 'SMJC',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${pop.className} bg-gray-100`}>
        {children}
        <Footer></Footer>
      </body>
    </html>
  )
}
